<font size=6  color=#003366> <b>LMAPR1492-Physique des matériaux </b> <br><br> 
<b>Tache n°6</b>

<div class="alert alert-danger">
<font size=4  color=#003366>  <b> Préparation</b>
</div>

Le matériau analysé est le mp-31454 dont la formule générale est TaSbRu. 

In [1]:
from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
import numpy as np

In [2]:
#Clé API utilisée
C = "ch7bMwOoOiiVhWKKKhy"

# Obtention des informations du matériau
with MPRester(C) as m:
    structure = m.get_structure_by_material_id("mp-31454")

# Définition de l'analyseur pour la maille primitive
SAP = SpacegroupAnalyzer(structure) 
    
# Définition de la maille conventionnelle
MC = SAP.get_conventional_standard_structure()
  
# Définition de l'analyseur pour la maille conventionelle
SAC = SpacegroupAnalyzer(MC)

<div class="alert alert-danger">
<font size=4  color=#003366>  <b> Symétrie n°1</b>
</div>

La première symétrie est une rotation d'ordre 2 autour de l'axe Z dans la maille conventionnelle. Elle est notée $(-x, -y, z)$.

Si on applique cette symétrie sur l'atome de Rutile situé en $(\frac{1}{4},\frac{1}{4},\frac{3}{4})$, il est envoyé en $(-\frac{1}{4},-\frac{1}{4},\frac{3}{4})$.

In [3]:
#Représentation matricielle de l'opération de symétrie 

S = SAC.get_symmetry_operations()[2]
S_RM = S.rotation_matrix
S_TV = S.translation_vector

print("Matrice de rotation")
print("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
print(S_RM)
print("")
print("Vecteur de translation")
print("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
print(S_TV)

Matrice de rotation
¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]

Vecteur de translation
¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨
[0. 0. 0.]


In [8]:
# Affichage de la symmétrie sur la maille conventionnelle 
QV= quick_view(MC)
display(QV)
QV.script('draw SYMOP "-x,-y,z" {1/4 1/4 3/4}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

<div class="alert alert-danger">
<font size=4  color=#003366>  <b> Symétrie n°2</b>
</div>

La deuxième symétrie est une réflexion par rapport au plan miroir noté $[\bar1,1,0]$ dans la maille conventionnelle . Elle est notée $(y, x, z)$.

Si on applique cette symétrie sur l'atome d'Antimoine situé en $(1,0,\frac{1}{2})$, il est envoyé en $(0,1,\frac{1}{2})$.

In [5]:
#Représentation matricielle de l'opération de symétrie 

S = SAC.get_symmetry_operations()[5]
S_RM = S.rotation_matrix
S_TV = S.translation_vector

print("Matrice de rotation")
print("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
print(S_RM)
print("")
print("Vecteur de translation")
print("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
print(S_TV)

Matrice de rotation
¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

Vecteur de translation
¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨
[0. 0. 0.]


In [14]:
# Affichage de la symmétrie sur la maille conventionnelle 
QV= quick_view(MC)
display(QV)
QV.script('draw SYMOP "y,x,z" {atomno=11}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

<div class="alert alert-danger">
<font size=4  color=#003366>  <b> Symétrie n°3</b>
</div>

La deuxième symétrie est une translation dans la maille conventionnelle. Elle est notée $(x+\frac{1}{2}, y+\frac{1}{2}, z)$.

Si on applique cette symétrie sur l'atome de Tantale situé en $(0,0,0)$, il est envoyé en $(\frac{1}{2},\frac{1}{2},0)$.

In [15]:
#Représentation matricielle de l'opération de symétrie 

S = SAC.get_symmetry_operations()[24]
S_RM = S.rotation_matrix
S_TV = S.translation_vector

print("Matrice de rotation")
print("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
print(S_RM)
print("")
print("Vecteur de translation")
print("¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨")
print(S_TV)

Matrice de rotation
¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Vecteur de translation
¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨
[0.5 0.5 0. ]


In [16]:
# Affichage de la symmétrie sur la maille conventionnelle 
QV= quick_view(MC)
display(QV)
QV.script('draw SYMOP "x+1/2,y+1/2,z" {atomno=1}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))